name: CI Test Suite

on: 
    push:
        branches: 
          - main
    pull_request: 
        branches: 
          - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set Up Go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.23

            - name: Install go-testreport
              run: go install github.com/becheran/go-testreport@v0.2.2

            - name:  Run Tests & Save JSON Output
              run: go test ./... -json > test-results.json

            - name: Generate and Publish Test Report
              run: go-testreport -input test-results.json -output $GITHUB_STEP_SUMMARY