name: CI Test Suite

on: 
    push:
        branches: 
          - main
    pull_request: 
        branches: 
          - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: 📥 Checkout Code
              uses: actions/checkout@v4

            - name: 🏗️ Set Up Go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.23

            - name: 📦 Install Dependencies
              run: go mod tidy

            - name: 📥 Install go-testreport (Pinned Version)
              run: |
                go install github.com/becheran/go-testreport@v0.2.2
                
            - name: 🛠️ Run Tests
              run: |
                go test ./... -json | go-testreport > test-results.json

            - name: 📊 Generate Test Report
              run: |
                go-testreport -json test-results.json -output $GITHUB_STEP_SUMMARY
